### ISSUE TITLE
Unserializable field should not throw error

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#45] opened 2019-09-24 07:21 UTC
when a field is not serializable, it should not throw an error but rather show an empty object or `[unserializable object]` in the data.

eg:

```
 "exception"  : {
     "$type"  :  "TypeError" ,
     "name"  :  "TypeError" ,
     "message"  :  "Cannot convert object to primitive value" ,
     "stack"  :  "TypeError: Cannot convert object to primitive value
    at Trait.invoke (/nodejsAction/XXJKBPJP/main.js:11351:71)
    at jsonifyForLog (/nodejsAction/XXJKBPJP/main.js:3199:47)
    at map (/nodejsAction/XXJKBPJP/main.js:9323:11)
    at map.next (<anonymous>)
    at each (/nodejsAction/XXJKBPJP/main.js:9151:26)
    at ./node_modules/ferrum/src/sequence.js.curry (/nodejsAction/XXJKBPJP/main.js:8911:5)
    at each [CURRY] (/nodejsAction/XXJKBPJP/main.js:7973:12)
    at obj (/nodejsAction/XXJKBPJP/main.js:9150:3)
    at ./node_modules/@adobe/openwhisk-action-utils/node_modules/@adobe/helix-log/src/serialize-json.js.JsonifyForLog.impl (/nodejsAction/XXJKBPJP/main.js:3209:38)
    at Trait.invoke (/nodejsAction/XXJKBPJP/main.js:11356:12)"
```

**Comment by koraa** [comment] 2019-09-24 11:21
Could you please provide an example for this and some example code that can be used to reproduce this?

**Comment by tripodsan** [comment] 2019-09-25 01:47
hmm...I can't reproduce it anymore ATM...

**Comment by koraa** [comment] 2019-09-25 13:15
Would you like to close this issue or keep it open as a remindert to try and reproduce this?

**Comment by tripodsan** [comment] 2019-09-26 00:51
close it for now.

**Comment by tripodsan** [comment] 2019-10-03 05:59
I found a way to reproduce this:

**Comment by koraa** [comment] 2019-10-04 12:37
So no exception thrown?

This is the expected behavior of the heuristic…it serializes to json unless the data can not be serialized.
We might consider a different heuristic, but I don't think it would be a good idea to just turn anything into json because it would drastically increase the space of false positives…

**Comment by tripodsan** [comment] 2019-10-05 10:14
using data-logging, we want explicitly use that data for logging. if a field happens to be not serializable, it should just be ignored.

**Closed** 2019-10-16 12:30 UTC
Labels: bug, invalid
